"""
Gherkin/BDD output builder: converts test cases to .feature file format.
Groups scenarios by Test Category as Feature blocks.
Each test case becomes a Scenario with Given/When/Then structure.
"""
from __future__ import annotations

import re


def _clean(text: str) -> str:
    return re.sub(r'\s+', ' ', str(text or "")).strip()


def _steps_to_gherkin(steps_text: str) -> list[str]:
    """Convert numbered steps to When / And lines."""
    raw = re.split(r'\n|\r|\d+[\.\)]\s+', steps_text)
    lines = [_clean(l) for l in raw if _clean(l)]
    if not lines:
        return ["    When the action is performed"]
    result = []
    for i, line in enumerate(lines):
        prefix = "When" if i == 0 else "And "
        result.append(f"    {prefix} {line}")
    return result


def build_gherkin(test_cases: list) -> str:
    """
    Convert a list of test case dicts to a Gherkin .feature file string.

    Groups by Test Category → Feature block.
    Each test case → Scenario with Given / When / Then.
    Tags include @TestLevel and @TestMethod.
    """
    if not test_cases:
        return "# No test cases to export\n"

    groups: dict[str, list] = {}
    for tc in test_cases:
        cat = _clean(tc.get("Test Category", "Functional")) or "Functional"
        groups.setdefault(cat, []).append(tc)

    lines: list[str] = ["# Generated by QA Test Cases Agent", ""]

    for feature_name, cases in groups.items():
        lines.append(f"Feature: {feature_name} Tests")
        lines.append("")

        for tc in cases:
            name        = _clean(tc.get("Test Case Name", "Test Scenario"))
            description = _clean(tc.get("Description", ""))
            precond     = _clean(tc.get("Precondition", "the system is in a valid state"))
            steps       = tc.get("Test Step Description", "")
            expected    = _clean(tc.get("Test Step Expected Result", "the operation succeeds"))
            level       = _clean(tc.get("Test Level", ""))
            method      = _clean(tc.get("Test Method", ""))
            confidence  = tc.get("_confidence", None)

            # Tags
            tags = []
            if level:
                tags.append(f"@{level.replace(' ', '_')}")
            if method:
                tags.append(f"@{method.replace(' ', '_')}")
            if confidence is not None and confidence < 60:
                tags.append("@needs_review")

            if tags:
                lines.append("  " + " ".join(tags))

            lines.append(f"  Scenario: {name}")

            if description:
                lines.append(f"    # {description}")

            lines.append(f"    Given {precond}")
            lines.extend(_steps_to_gherkin(steps))
            lines.append(f"    Then {expected}")
            lines.append("")

        lines.append("")

    return "\n".join(lines)
